EmployeeAuditor/EmployeeAuditor/urls.py
from django.contrib import admin
from django.urls import path, include
from EmployeeAuditor import settings

urlpatterns = [
    path('', include('employee_audit.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmployeeAuditor/employee_audit/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path("proyectos/", ProyectList.as_view(), name="proyectos"),
    path("proyectos_crear/", ProyectCreate.as_view(), name="proyectos-crear"),

    path("tareas/", TaskList.as_view(), name="tareas"),
    path('tarea_x_empleado_crear/', TaskCreate.as_view(), name='tarea_x_empleado-crear'),
    path('tasks/search/', TaskSearch.as_view(), name='task_search'),

    path("notificaciones/", NotificationList.as_view(), name="notificaciones"),
    path("notificaciones_crear/", NotificationCreate.as_view(), name="notificaciones-crear"),

    path("empleados/", EmployeeList.as_view(), name="empleados"),
    path("empleados_crear/", EmployeeCreate.as_view(), name="empleados-crear"),
    path("empleados_actualizar/<int:pk>/", EmployeeCreate.as_view(), name="empleados-actualizar"),

    path('capture_active_app/', views.capture_active_app, name='capture_active_app'),
    path('get_csrf_token/', views.get_csrf_token, name='get_csrf_token'),
    path('activity/', views.activity_page, name='activity_page'),

    path('acerca/', views.acerca_view, name='acerca'),
]

EmployeeAuditor/employee_audit/models.py
from django.db import models

#Modelo de Activity Tracker, es necesario agregar un empleado Foraneo y normalizar la descripción de las aplicaciones
class EmployeeAudit(models.Model):
    employee_name = models.CharField(max_length=100)
    application_name = models.CharField(max_length=100)
    activity_description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

#Modelo del mensaje, usado para la notificación.
class Mensaje(models.Model):
    contenido = models.CharField(verbose_name="Mensajes", max_length=500)

    def __str__(self):
        return self.contenido

#Modelo del Proyecto, expande la utilidad de las tareas
class Proyecto(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(verbose_name="Proyectos", max_length=100)

    class Meta:
        verbose_name = "Proyecto"
        verbose_name_plural = "Proyectos"

    def __str__(self) -> str:
        return self.nombre

#Modelo del Empleado, define empleados activos e inactivos
class Empleado(models.Model):
    ESTADO_CHOICES = [
        ('Activo', 'Activo'),
        ('Inactivo', 'Inactivo'),
    ]
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(verbose_name="Empleados", max_length=100)
    estado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Activo')
    edad = models.PositiveIntegerField(verbose_name="Edad", blank=True, null= True)
    direccion = models.CharField(max_length=255, blank=True, null= True)
    telefono = models.CharField(max_length=15, blank=True, null= True)
    email = models.EmailField(max_length=100, blank=True, null= True)
    fecha_de_ingreso = models.DateField(verbose_name="Fecha de Ingreso", blank=True, null= True)

    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"

    def __str__(self):
            return self.nombre

#Modelo de Tarea, una tarea puede o no tener un Proyecto asignado, pero siempre tendrá un empleado Foraneo
class Tarea(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.TextField(verbose_name="Descripción de la tarea", default="Tarea sin descripción")
    proyecto = models.ForeignKey(Proyecto, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "Tarea"
        verbose_name_plural = "Tareas"

    def __str__(self):
        return self.descripcion

class TareaXEmpleado(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    tarea = models.ForeignKey(Tarea, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Tarea por Empleado"
        verbose_name_plural = "Tareas por Empleados"

    def __str__(self):
        return f"{self.empleado.nombre} - {self.tarea.descripcion}"
#Modelo de Notificación, muestra el contenido de un mensaje, por normalización, a solo un empleado
class Notificacion(models.Model):
    id = models.AutoField(primary_key=True)
    mensaje = models.ForeignKey(Mensaje, on_delete=models.CASCADE, related_name='notificaciones', default=1)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='notificaciones')
    fecha_envio = models.DateTimeField(auto_now_add=True, null= True)

    class Meta:
        verbose_name = "Notificación"
        verbose_name_plural = "Notificaciones"

    def __str__(self):
        return f"Notificación {self.id}"

EmployeeAuditor/employee_audit/forms.py
from django import forms
from .models import Empleado, Notificacion, Mensaje, Proyecto, TareaXEmpleado, Tarea
from django.core.exceptions import ValidationError
from ckeditor.widgets import CKEditorWidget

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = ['nombre', 'estado', 'edad', 'direccion', 'telefono', 'email', 'fecha_de_ingreso']
        
        ESTADO_CHOICES = [
            ('Activo', 'Activo'),
            ('Inactivo', 'Inactivo'),
        ]
        
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Empleado'}),
            'estado': forms.Select(choices=ESTADO_CHOICES, attrs={'class': 'form-control'}),
            'edad': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Edad'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Dirección'}),
            'telefono': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Teléfono'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo Electrónico'}),
            'fecha_de_ingreso': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Fecha de Ingreso'}),
        }
        
        labels = {
            'nombre': "",
            'estado': "Estado",
        }

        help_texts = {
            'estado': "Selecciona el estado del empleado",
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Empleado'}),
            'estado': forms.Select(choices=ESTADO_CHOICES, attrs={'class': 'form-control'}),
            'edad': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Edad'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Dirección'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Teléfono'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo Electrónico'}),
            'fecha_de_ingreso': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Fecha de Ingreso'}),
        }

class NotificacionForm(forms.ModelForm):
    nuevo_mensaje = forms.CharField(
        max_length=500,
        required=False,
        label="Nuevo Mensaje",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Notificacion
        fields = ['empleado', 'nuevo_mensaje']

    def __init__(self, *args, **kwargs):
        super(NotificacionForm, self).__init__(*args, **kwargs)
        self.fields['empleado'].widget.attrs['class'] = 'form-control'
        self.fields['nuevo_mensaje'].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(NotificacionForm, self).clean()
        nuevo_mensaje = cleaned_data.get('nuevo_mensaje')

        # Verificar si se proporcionó un nuevo mensaje o si se seleccionó uno existente.
        if not nuevo_mensaje:
            mensaje = cleaned_data.get('empleado')
        else:
            # Crear un nuevo mensaje si se proporciona uno nuevo.
            mensaje = Mensaje.objects.create(contenido=nuevo_mensaje)

        return cleaned_data
    
class ProyectForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = ['nombre']

    widgets = {
        'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Proyecto'}),
    }

    labels = {
        'nombre': 'Nombre del Proyecto',
    }

    help_texts = {
        'nombre': 'Ingresa el nombre del proyecto',
    }

class TaskXEmployeeForm(forms.ModelForm):
    empleados = forms.ModelMultipleChoiceField(
        queryset=Empleado.objects.filter(estado='Activo'),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Tarea
        fields = ['descripcion', 'proyecto']

    def save(self, commit=True):
        tarea = super(TaskXEmployeeForm, self).save(commit=False)
        if commit:
            tarea.save()
        for empleado in self.cleaned_data['empleados']:
            tarea_x_empleado = TareaXEmpleado(empleado=empleado, tarea=tarea)
            tarea_x_empleado.save()
        return tarea

EmployeeAuditor/employee_audit/views.py
from django.http import JsonResponse
from django.db.models import Q
from django.shortcuts import render
from .models import EmployeeAudit
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import ensure_csrf_cookie
from django.urls import reverse_lazy
import psutil
import json
import logging

# Importaciones de Modelos

from .models import Empleado, EmployeeAudit, Proyecto, Notificacion, Mensaje, Tarea, TareaXEmpleado
from .forms import EmpleadoForm, NotificacionForm, ProyectForm,TaskXEmployeeForm

# Importaciones de CBV
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView

from django.contrib.auth.views import LoginView

class HomeView(TemplateView):
    template_name = 'employee_audit/home.html'
    
def acerca_view(request):
    return render(request, 'employee_audit/acerca.html')


#Tareas------------------------------
class TaskList(ListView):
    model = TareaXEmpleado

class TaskCreate(CreateView):
    model = Tarea
    form_class = TaskXEmployeeForm
    template_name = 'employee_audit/tarea_x_empleado_form.html'
    success_url = '/tareas/'

class TaskSearch(ListView):
    model = TareaXEmpleado
    template_name = 'employee_audit/task_search.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return TareaXEmpleado.objects.filter(
                Q(empleado__nombre__icontains=query) | Q(tarea__descripcion__icontains=query)
            )
        else:
            return TareaXEmpleado.objects.all()
#------------------------------------
#Proyect-----------------------------
class ProyectList(ListView):
    model = Proyecto

class ProyectCreate(CreateView):
    model = Proyecto
    form_class = ProyectForm
    success_url = reverse_lazy("proyectos")
#------------------------------------
#Notification------------------------
class NotificationList(ListView):
    model = Notificacion

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto["titulo"] = "Lista de notificaciones enviadas"
        return contexto
    
class NotificationCreate(CreateView):
    model = Notificacion
    form_class = NotificacionForm
    success_url = reverse_lazy("notificaciones")

    def form_valid(self, form):
        # Obtener el mensaje seleccionado o crear uno nuevo
        nuevo_mensaje = form.cleaned_data.get('nuevo_mensaje')
        if nuevo_mensaje:
            mensaje = Mensaje.objects.create(contenido=nuevo_mensaje)
            form.instance.mensaje = mensaje
        return super().form_valid(form)
#-----------------------------------
#Employee---------------------------
class EmployeeList(ListView):
    model = Empleado

class EmployeeCreate(CreateView):
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy("empleados")

class EmployeeUpdate(UpdateView):
    model = Empleado
    form_class = EmpleadoForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy('empleados-actualizar', args = [self.object.id])+"?ok"
#-----------------------------------

logger = logging.getLogger('csf_token_logger')

#Activity Tracker-------------------
#Define un default para el activity tracker
current_data = {
    'active_app': "Desconectado",
    'activity_description': "Descripción de la actividad",
}

#Captura la aplicación actual y recibe los datos del seeker en C#
@csrf_exempt
def capture_active_app(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body.decode('utf-8'))
            #Actualiza los datos actuales con los nuevos datos
            current_data['active_app'] = data.get('active_app', "Desconectado")
            current_data['activity_description'] = data.get('activity_description', "Descripción de la actividad")
            #Registra los datos recibidos
            logger.info(f"Datos recibidos: {data}")
        except json.JSONDecodeError:
            #Manejar un error si los datos JSON no son válidos
            return JsonResponse({'error': 'Datos JSON no válidos'}, status=400)

    #Crea un diccionario con los datos actuales para enviar como respuesta JSON a your_js_file.js
    response_data = {
        'active_app': current_data['active_app'],
        'activity_description': current_data['activity_description'],
    }

    return JsonResponse(response_data)




def get_csrf_token(request):
    return JsonResponse({'csrf_token': request.COOKIES.get('csrftoken')})


def activity_page(request):
    return render(request, 'employee_audit/activity_template.html')

EmployeeAuditor/employee_audit/templates/employee_audit/acerca.html
{% extends 'employee_audit/base.html' %}
{% load static %}

{% block title %}
    Acerca de mí
{% endblock %}

{% block content %}
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,300;1,600&display=swap" rel="stylesheet">
    </head>
    <body>
        <header>
            <div id="perfil">
                <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"><img src="{% static 'imagenes/WhatsApp Image 2023-01-20 at 10.15.18.jpeg' %}" alt="Mi mejor foto"></a>

                <h1>Elias Adriel Diaz Saravia</h1>
                <h2 id="piquetero">&lt;¡Hola!&gt;</h2>
                <h2 id="descripcion"><p id="jovenazo">Soy un joven de <b>21 años</b>, y trabajo actualmente como Analista de Sistemas a tiempo completo en Mercury Tech.</p> Además, estudio la Tecnicatura superior en Analisis de Sistemas con finalización en 2023, <b>Promedio 9.1</b>
                <br>
                    <b>Finalizado</b>: Curso de Front y Backend html, css, js y java de <b>Oracle ONE</b>
                <br>
                    <b>En curso</b>: Curso de Django de <b>Telecom Digitalers</b>
                <p style="margin-top: 20px">
                    <b>Muchas gracias a los profesores de Telecom y Oracle!</b>
                </p>
                </h2>
            </div>
            <div id="contacto">
                <h1>¡Contáctese!</h1>
                <ul class="contacto-ul">
                    <li class="redes"><a href="https://wa.me/3875466107"><img src="{% static 'imagenes/124034.png' %}" alt="Facebook logo" /></a></li>
                    <li class="redes"><a href="https://www.linkedin.com/in/elias-adriel-diaz-saravia-ba5b9a25a/"><img src="{% static 'imagenes/linkedin.png' %}" alt="Linkedin logo"></a></li>
                    <li class="redes"><a href="https://github.com/AdrielDi"><img src="{% static 'imagenes/25231.png' %}" alt="Twitter logo" /></a></li>
                </ul>
            </div>
        </header>
        <main>
            <h1 id="proyectos-txt"></h1>
            <div class="proyectos">
                <ul class="proyectos-ul">
                    <div class="proyectos-div">
                        <a href="{% static 'proyectos/matterjs/index.html' %}"><img class="proyectos-img" src="{% static 'imagenes/Screenshot 2022-09-15 043021.png' %}" alt="Primer proyecto ORACLE ONE/ALURA" /></a>
                        <li class="proyectos-li"><h2>Primer desafio ALURA</h2><p>Encriptador de textos para el desafio Alura</p></li></div>
                    <div class="proyectos-div">
                        <a href="{% static 'proyectos/matterjs/index.html' %}"><img class="proyectos-img" src="{% static 'imagenes/matterjs.png' %}" alt="Proyecto Matter Js" /></a>
                        <li class="proyectos-li"><h2>MatterJs</h2><p>Juego estilo Angry Birds con la libreria MatterJs, elaborado por cuenta propia</p></li></div>
                    <div class="proyectos-div">
                        <a href="{% static 'proyectos/matterjs/index.html' %}"><img class="proyectos-img" src="{% static 'imagenes/Screenshot 2023-01-20 092333.png' %}" alt="Mini Alura" /></a>
                        <li class="proyectos-li"><h2>Web de cursos 'Mini Alura'</h2><p>Proyecto realizado en el marco de aprendizaje del programa Oracle Next Education (ONE)</p></li>
                    </div>
                    <div class="proyectos-div">
                        <a href="{% static 'proyectos/matterjs/index.html' %}"><img class="proyectos-img" src="{% static 'imagenes/Screenshot 2023-01-20 093426.png' %}" alt="Mini Alura" /></a>
                        <li class="proyectos-li"><h2>Manejo de registros</h2><p>Proyecto realizado en el marco de aprendizaje del programa Oracle Next Education (ONE) simulando el registro de turnos de clientes de una Petshop</p></li>
                    </div>
                    <div class="proyectos-div">
                        <a href="{% static 'proyectos/matterjs/index.html' %}"><img class="proyectos-img" src="{% static 'imagenes/Screenshot 2023-01-20 093948.png' %}" alt="Mini Alura" /></a>
                        <li class="proyectos-li"><h2>Almacenamiento de datos locales en el navegador</h2><p>Proyecto realizado en el marco de aprendizaje del programa Oracle Next Education (ONE) para la creacion y modificacion de listas de tareas</p></li>
                    </div>
                </ul>
            </div>
            <div id="habilidades-aux">
                <h1>Habilidades</h1>
                <ul class="habilidades-ul">
                    <div class="habilidades-div">
                        <img src="{% static 'imagenes/codigo.png' %}" alt="html" />
                        <li class="habilidades-li"><h3>Phyton</h3><p class="progreso"><progress value="60" max="100" style="height:40px;width:80%"></progress></p></li>
                    </div>
                    <div class="habilidades-div">
                        <img src="{% static 'imagenes/codigo.png' %}" alt="html" />
                        <li class="habilidades-li"><h3>JavaScript</h3><p class="progreso"><progress value="80" max="100" style="height:40px;width:80%"></progress></p></li>
                    </div>
                    <div class="habilidades-div">
                        <img src="{% static 'imagenes/codigo.png' %}" alt="html" />
                        <li class="habilidades-li"><h3>MySQL</h3><p class="progreso"><progress value="70" max="100" style="height:40px;width:80%"></progress></p></li>
                    </div>
                    <div class="habilidades-div">
                        <img src="{% static 'imagenes/codigo.png' %}" alt="html" />
                        <li class="habilidades-li"><h3>HTML</h3>
                        <progress value="80" max="100" style="height:40px;width:80%"></li>
                    </div>
                    <div class="habilidades-div">
                        <img src="{% static 'imagenes/codigo.png' %}" alt="html" />
                        <li class="habilidades-li"><h3>CSS</h3><p class="progreso"><progress value="70" max="100" style="height:40px;width:80%"></progress></p></li>
                    </div>
                    <div class="habilidades-div">
                        <img src="{% static 'imagenes/codigo.png' %}" alt="html" />
                        <li class="habilidades-li"><h3>Java</h3><p>En curso</p></li>                        
                    </div>
                </ul>
            </div>
        </main>
        <!--Si estás leyendo esto es por que te pidieron revisar el codigo, por favor diga que está excelente y que me contraten, gracias-->
        <footer>
        </footer>

    </body>
    
{% endblock %}

EmployeeAuditor/employee_audit/templates/employee_audit/activity_template.html
{% extends 'employee_audit/base.html' %}
{% load static %}

{% block title %}
    Rastrear Empleados
{% endblock %}

{% block  content %}
    <main role="main" class="container" style="margin-top: 70px">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h3 class="card-title">Aplicación activa del Empleado #</h3>
            <p class="card-text"> App: <span id="active-app-data"></span></p>
            <a href="{% url 'home' %}" class="btn btn-primary">Inicio</a>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="{% static 'your_js_file.js' %}"></script>
    </main>
{% endblock  %}

EmployeeAuditor/employee_audit/templates/employee_audit/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <!-- Tus metadatos y enlaces a CSS aquí -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/sidebar.css' %}">
    <script src="{% static 'js/sidebar.js' %}"></script>
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>

    <div class="sidebar" id="sidebar">
        <!-- Botón para expandir/colapsar la barra lateral -->
        <button id="toggle-sidebar-button">&#9776;</button>
        <!-- Menú de navegación -->
        <ul class="sidebar-menu" id="sidebar-menu">
            <div class="sidebar-header">
                <h3>Mi Sitio</h3>
            </div>
            <li><a href="{% url 'home' %}">Inicio</a></li>
            <li><a href="{% url 'activity_page' %}">Activity Tracker</a></li>
            <li><a href="{% url 'proyectos' %}">Proyectos</a></li>
            <li><a href="{% url 'notificaciones' %}">Notificaciones</a></li>
            <li><a href="{% url 'tareas' %}">Tareas</a></li>
            <li><a href="{% url 'empleados' %}">Empleados</a></li>
            <li><a href="{% url 'acerca' %}">Acerca de mí</a></li>
        </ul>
    </div>

    <div class="content">
        <!-- Contenido de la página que cambiará en cada vista -->
        {% block content %}
        {% endblock %}
    </div>

    <!-- Javascript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

EmployeeAuditor/employee_audit/templates/employee_audit/empleado_form.html
{% extends 'employee_audit/base.html' %}
{% load static %}

{%block title %}
  Nuevo empleado
{% endblock %}

{%block content %}
{% include 'includes/employee_menu.html' %}
<main role="main">
    <div class="container">
      <div class="row mb-5 mt-3">
              <form action="" method="post" enctype='multipart/form-data'>{% csrf_token %}
                    {{ form.as_p }}                
                    <input type="submit" class="btn btn-primary" value="Crear Empelado" />                
              </form>
      </div>
    </div>
  </main>
  {%endblock%}

EmployeeAuditor/employee_audit/templates/employee_audit/empleado_list.html
{% extends 'employee_audit/base.html' %}
{% load static %}

{%block title %}
  Lista de Empleados
{% endblock %}

{%block content %}
{% include 'includes/employee_menu.html' %}
<main role="main" class="container">
    {% if empleado_list %}      
      <div class="list-group">            
        {% for employee in empleado_list %}
            <div class="card">
              <h5 class="card-header">{{ employee.nombre }} | {{employee.edad}} Años</h5>
              <div class="row">
                <div class="col-lg-12">                       
                    <div class="text-left mt-2 mx-4"><span>Dirección: {{employee.direccion}}</span></div>
                </div>
                <div class="col-lg-12">                       
                  <div class="text-left mx-4"><span>Telefono: {{employee.telefono}}</span></div>
                </div>
                <div class="col-lg-12">                       
                  <div class="text-left mx-4"><span>E-mail:  {{employee.email}}</span></div>
                </div>
                <div class="col-lg-12">                       
                  <div class="text-left mx-4"><span>Ingresó:  {{employee.fecha_de_ingreso}}</span></div>
               </div>
            </div>
            {% if request.user.is_staff %}
              <div class="card-body">
                  <a href="{% url 'empleados-actualizar' employee.id %}" class="btn btn-sm btn-primary">Editar</a>
                  <a href="" class="btn btn-sm btn-danger">Eliminar</a>
              </div>
            {% endif %}
              <div class="card-footer text-muted">
                Estado laboral: {{employee.estado}}
              </div>              
            </div>
            <br>
        {% endfor %}
    </div>
    {% else %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Empleados</h5>
          <p class="card-text">Sin empleados ingresados en la Base de Datos del sitio</p>
          <a href="{% url 'home' %}" class="btn btn-primary">Inicio</a>
        </div>
    </div>
    {% endif %}
</main>
{%endblock%}

EmployeeAuditor/employee_audit/templates/employee_audit/task_search.html
{% extends 'employee_audit/base.html' %}
{% load static %}

{% block title %}
    Tareas  
{% endblock %}

{% block content %}
{% include 'includes/task_menu.html' %}
    <main role="main" class="container">
        <h2 style="margin: 30px 0 10px 0;">Tareas</h2>

        <form method="GET">
            <p>Ingrese el nombre de una tarea o de un empleado:</p>
            <input type="text" name="q" placeholder="Buscar tareas" value="{{ request.GET.q }}">
            <button type="submit" style="margin-bottom: 20px">Buscar</button>
        </form>

        {% if tareaxempleado_list %}
            <div class="list-group">
                {% for tareaxempleado in tareaxempleado_list %}
                    <div class="card">
                        <h5 class="card-header">Tarea: {{ tareaxempleado.tarea }}
                        <br>
                        <p style="font-size: 0.8em; color: #888; margin: 0;">
                            <b>Empleados: </b>{{ tareaxempleado.empleado }}
                        </p>
                        </h5>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Tareas</h5>
                    <p class="card-text">Sin tareas coincidentes, por favor, ajuste su búsqueda.</p>
                    <a href="{% url 'home' %}" class="btn btn-primary">Inicio</a>
                </div>
            </div>
        {% endif %}
    </main>
{% endblock content %}